import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Form from '@/components/Form'
import Account from '@/components/Account'
import Bottom from '@/components/Footer'
import GetApp from '@/components/GetApp'

export default function Home() {
  return (
    <>
      <Head>
        <title>Woroking here</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.body}>
        <main className={`${styles.main}`}>
          <Form/>
          <Account/>
          <GetApp/>
        </main>
        <footer className={`${styles.Footer}`}>
          <Bottom/>
        </footer>
      </div>
    </>
  )
}
