import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Form from '@/components/Form'
import Words from '@/components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Woroking here</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <Form/>
      </main>
      <footer className={`${styles.main}`}>
        <Words/>
      </footer>
      
    </>
  )
}
