import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Form from '@/components/Form'
import Account from '@/components/Account'
import Bottom from '@/components/Footer'
import GetApp from '@/components/GetApp'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Woroking here</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className={styles.body}>
        <main className={`${styles.main}`}>
          <div className={styles.mainImage}>
            <Image src={'/images/home_phone.png'} width={380} height={580} alt='Phones dsiplaying the instagram home screen'/>
          </div>
          <div className={styles.mainContent}>
            <Form/>
            <Account/>
            <GetApp/>
          </div>
        </main>
        <footer className={`${styles.Footer}`}>
          <Bottom/>
        </footer>
      </div>
    </>
  )
}
